# Topic Naming with OpenAI

Loads the BERTopic models and their topic info produced in `02-topic_model/`,
sends representative documents per cluster to GPT to obtain:

1. A **description** of each topic cluster.
2. An **enhanced (synthesised) description**.
3. A short **cluster name**.

Prompts are loaded from `prompts.yaml`. Results are saved as TSV files alongside
the topic models in `assets/topic_models/`.

In [1]:
import os
import yaml
import numpy as np
import pandas as pd
from openai import OpenAI

In [2]:
# ── CONFIG ────────────────────────────────────────────────────────────────────
ASSETS_DIR     = os.path.join('..', 'assets')
MODELS_DIR     = os.path.join(ASSETS_DIR, 'topic_models')
EMBEDDINGS_DIR = os.path.join(ASSETS_DIR, 'embeddings')

# Number of representative documents to send per cluster
TOP_N_DOCS = 5

# OpenAI model
MODEL = 'gpt-4.1-nano'

# ── Load prompts ──────────────────────────────────────────────────────────────
with open('prompts.yaml') as f:
    prompts = yaml.safe_load(f)

THEME = prompts['theme']
THEME_DESCRIPTION = prompts['theme_description']

print(f'Theme: {THEME}')
print(f'Description: {THEME_DESCRIPTION[:80]}...')

Theme: Synthetic Biology
Description: Synthetic biology is an interdisciplinary field that combines principles from bi...

In [3]:
# ── OpenAI client ─────────────────────────────────────────────────────────────
api_key = open('openai.key').read().strip()
client = OpenAI(api_key=api_key)

## 1. Load topic models and corpora

In [4]:
# Topic-level info (from BERTopic's get_topic_info())
teams_info  = pd.read_csv(os.path.join(MODELS_DIR, 'teams_topic_info.txt'),  sep='\t')
papers_info = pd.read_csv(os.path.join(MODELS_DIR, 'papers_topic_info.txt'), sep='\t')

# Document-level topic assignments
teams_doc_topics  = pd.read_csv(os.path.join(MODELS_DIR, 'teams_doc_topics.txt'),  sep='\t')
papers_doc_topics = pd.read_csv(os.path.join(MODELS_DIR, 'papers_doc_topics.txt'), sep='\t')

# Full corpora (with text)
teams_corpus  = pd.read_csv(os.path.join(EMBEDDINGS_DIR, 'teams_corpus.txt'),  sep='\t')
papers_corpus = pd.read_csv(os.path.join(EMBEDDINGS_DIR, 'papers_corpus.txt'), sep='\t')

# Merge text into doc-topics
teams_df  = teams_doc_topics.merge(teams_corpus,  on='UT', how='left')
papers_df = papers_doc_topics.merge(papers_corpus, on='id', how='left')

print(f'Teams:  {len(teams_df):,} docs, {teams_info.Topic.max() + 1} topics')
print(f'Papers: {len(papers_df):,} docs, {papers_info.Topic.max() + 1} topics')

Teams:  4,548 docs, 161 topics
Papers: 24,202 docs, 263 topics

## 2. Helper functions

In [5]:
def ask_gpt(
    system_prompt: str,
    user_prompt: str,
    model: str = MODEL,
    temperature: float = 0.1,
    max_tokens: int = 500,
) -> str:
    """Send a system + user prompt to OpenAI and return the assistant reply."""
    response = client.chat.completions.create(
        model=model,
        temperature=temperature,
        max_tokens=max_tokens,
        messages=[
            {'role': 'system', 'content': system_prompt},
            {'role': 'user',   'content': user_prompt},
        ],
    )
    return response.choices[0].message.content


def get_representative_texts(df: pd.DataFrame, topic_id: int, top_n: int = TOP_N_DOCS) -> str:
    """Return the top-N documents of a topic joined with ##### separators.

    The text is truncated to ~14 000 chars (~3 500 tokens) to stay within
    context limits.
    """
    subset = df[df['topic'] == topic_id]
    texts = subset['text'].head(top_n).tolist()
    bulk = ' ##### '.join(texts)
    return bulk[:14_000]


def fmt_prompt(template: str, **kwargs) -> str:
    """Format a prompt template with the given keyword arguments."""
    result = template
    for key, value in kwargs.items():
        result = result.replace('{' + key + '}', str(value))
    return result

In [6]:
def name_topics(
    df: pd.DataFrame,
    topic_info: pd.DataFrame,
) -> pd.DataFrame:
    """For each non-outlier topic, get description, enhanced description, and name.

    Returns a DataFrame with columns: topic, description, enhanced_description, name.
    """
    p_desc = prompts['cluster_description']
    p_enh  = prompts['cluster_description_enhanced']
    p_name = prompts['cluster_name']

    rows = []
    topic_ids = sorted(topic_info[topic_info['Topic'] != -1]['Topic'].unique())

    for tid in topic_ids:
        print(f'  Topic {tid} ...', end=' ', flush=True)
        cluster_text = get_representative_texts(df, tid)

        # Step 1: cluster description
        description = ask_gpt(
            system_prompt=fmt_prompt(p_desc['system'], theme=THEME, theme_description=THEME_DESCRIPTION),
            user_prompt=fmt_prompt(p_desc['user'], cluster_text=cluster_text),
            temperature=0.2,
        )

        # Step 2: enhanced (synthesised) description
        enhanced = ask_gpt(
            system_prompt=fmt_prompt(p_enh['system'], theme=THEME),
            user_prompt=fmt_prompt(p_enh['user'], cluster_description=description),
            temperature=0.1,
        )

        # Step 3: short name
        name = ask_gpt(
            system_prompt=fmt_prompt(p_name['system'], theme=THEME, theme_description=THEME_DESCRIPTION),
            user_prompt=fmt_prompt(p_name['user'], cluster_description=description),
            max_tokens=60,
            temperature=0.3,
        )
        name = name.strip().strip('"').strip("'")

        print(name)
        rows.append({
            'topic': tid,
            'name': name,
            'description': enhanced,
            'raw_description': description,
        })

    return pd.DataFrame(rows)

## 3. Name iGEM Teams topics

In [7]:
print('Naming iGEM Teams topics...')
teams_names = name_topics(teams_df, teams_info)
teams_names

Naming iGEM Teams topics...
  Topic 0 ... Synthetic Biology-Enabled Disease Diagnostics and Biosensing Technologies
  Topic 1 ... Light-Inducible Systems
  Topic 2 ... Synthetic Biology for Microbial Detection and Biofilm Control
  Topic 3 ... Synthetic Biology for PET Plastic Degradation and Recycling
  Topic 4 ... Synthetic Biology for Cancer and Disease Therapeutics
  Topic 5 ... Microbial Diagnostic and Therapeutic Platforms
  Topic 6 ... Synthetic Biology for Diagnostic and Therapeutic Biosystems
  Topic 7 ... Synthetic Biology for Genetic Control and Diagnostics
  Topic 8 ... Synthetic Biology Design and Automation
  Topic 9 ... Synthetic Biology Tools for Genetic and Molecular Control
  Topic 10 ... Synthetic Biology for Sustainable Environmental and Resource Solutions
  Topic 11 ... Synthetic Biology Diagnostics
  Topic 12 ... Synthetic Biology for Environmental and Health Monitoring
  Topic 13 ... Bioproduction and Cellular Engineering
  Topic 14 ... Bioactive Compound Synthesis
  Topic 15 ... Synthetic Biology for Diabetes
  Topic 16 ... Synthetic Biology for Biological Computing
  Topic 17 ... Synthetic Biology Biosensors for Environmental Monitoring
  Topic 18 ... Synthetic Biology for Environmental Sustainability and Community Engagement
  Topic 19 ... Synthetic Biology for Cardiovascular and Metabolic Disease Therapy
  Topic 20 ... Sustainable Bioproduction Cluster
  Topic 21 ... Synthetic Biology for Microbial Bioenergy
  Topic 22 ... Synthetic Biology for Phosphate Recycling
  Topic 23 ... Synthetic Biology for Environmental Remediation and Sustainable Biomanufacturing
  Topic 24 ... Synthetic Biology for Space Sustainability
  Topic 25 ... Synthetic Biology for Tissue Regeneration
  Topic 26 ... Synthetic Biology for Therapeutic and Immunotherapeutic Applications
  Topic 27 ... Synthetic Biology for Environmental Sustainability
  Topic 28 ... Synthetic Biology for Antimicrobial Resistance
  Topic 29 ... Synthetic Biology for Metal Recycling
  Topic 30 ... Synthetic Biology for Water Safety
  Topic 31 ... Synthetic Biology for Cadmium Detection and Remediation
  Topic 32 ... Synthetic Biology for Mosquito Control
  Topic 33 ... Synthetic Biology for Environmental Water Management
  Topic 34 ... Spider Silk Bioengineering
  Topic 35 ... Phage Engineering for Synthetic Biology
  Topic 36 ... Synthetic Biology in Vaccine Development
  Topic 37 ... Synthetic Biology for Radiation Detection and Protection
  Topic 38 ... Synthetic Biology for Biosafety and Environmental Containment
  Topic 39 ... Synthetic Genome Engineering Tools
  Topic 40 ... Synthetic Biology for Sustainable Bioenergy
  Topic 41 ... Synthetic Biology Diagnostic Biosensors
  Topic 42 ... Synthetic Biology-Driven Therapeutic Cell Engineering
  Topic 43 ... Gut-Brain Synthetic Biology
  Topic 44 ... RNAi in Synthetic Biology
  Topic 45 ... Sustainable Dyeing and Responsive Systems
  Topic 46 ... Synthetic Biology for Food, Materials, and Sustainable Production
  Topic 47 ... Synthetic Biology for Environmental and Energy Sustainability
  Topic 48 ... Synthetic Biology for Environmental Pollution Detection and Remediation
  Topic 49 ... Synthetic Biology for Biological System Engineering
  Topic 50 ... Synthetic Biology for Greenhouse Gas Mitigation
  Topic 51 ... Synthetic Biology for Cancer Diagnostics and Therapy
  Topic 52 ... Environmental Biosensing and Bioremediation
  Topic 53 ... Synthetic Biology for Pest and Disease Control
  Topic 54 ... Magnetically Responsive Synthetic Biological Systems
  Topic 55 ... Heavy Metal Biosensors
  Topic 56 ... Synthetic Biology for Acne and Skincare Innovation
  Topic 57 ... Yeast Synthetic Biology for Industrial Biotechnology
  Topic 58 ... Synthetic Biology for Neurodegenerative Diseases
  Topic 59 ... Sustainable Materials and Conservation
  Topic 60 ... Synthetic Biology for Plant Disease Management
  Topic 61 ... Synthetic Biological Memory and Logic Circuits
  Topic 62 ... Synthetic Biology for Nutritional Enhancement
  Topic 63 ... Synthetic Biology for Honeybee Health and Pesticide Detoxification
  Topic 64 ... Synthetic Biology for Advanced Biological Systems and Therapeutics
  Topic 65 ... Microbial Engineering for Bioproduction
  Topic 66 ... Probiotic Synthetic Biology
  Topic 67 ... Microbial Bio-Compound Engineering
  Topic 68 ... Synthetic Biology for Allergy and Inflammatory Disease Therapeutics
  Topic 69 ... Synthetic Biology for Oral Health
  Topic 70 ... Synthetic Biology VOC Biosensors
  Topic 71 ... Environmental Synthetic Biology
  Topic 72 ... Synthetic Biology for Plant Disease Detection and Control
  Topic 73 ... Synthetic Biology for Sustainable Biological Solutions
  Topic 74 ... Synthetic Biology for Environmental Sustainability
  Topic 75 ... Synthetic Biology-Driven Fragrance Biosynthesis
  Topic 76 ... Synthetic Biology for Hair Health and Treatment
  Topic 77 ... Synthetic Biology for Aquaculture and Environmental Monitoring
  Topic 78 ... Synthetic Biology for Therapeutic Peptide and Protein Engineering
  Topic 79 ... Synthetic Biology for Therapeutics and Viral Intervention
  Topic 80 ... Synthetic Biology for Data Storage and Security
  Topic 81 ... Climate-Resilient Agriculture
  Topic 82 ... Synthetic Biology for Therapeutic and Biomedical Applications
  Topic 83 ... Environmental Bioremediation
  Topic 84 ... Synthetic Biology for Sugar and Taste Innovation
  Topic 85 ... Environmental Synthetic Biology
  Topic 86 ... Synthetic Biological Time Control and Cellular Engineering
  Topic 87 ... Redox and Chemical Sensing Systems
  Topic 88 ... Temperature-Responsive Synthetic Biological Systems
  Topic 89 ... Environmental and Food Safety Biosensors
  Topic 90 ... Synthetic Biology for Ecosystem Engineering
  Topic 91 ... Synthetic Biology for Environmental Remediation and Bioenergy
  Topic 92 ... Sustainable Biofuel and Bioproducts
  Topic 93 ... Genetic Tool Development
  Topic 94 ... Synthetic Biology Applications
  Topic 95 ... Synthetic Biology for Cancer Detection and Therapy
  Topic 96 ... Synthetic Biology for Coral Reef Conservation
  Topic 97 ... Copper Biosensing and Bioremediation
  Topic 98 ... Quorum Sensing in Synthetic Biology
  Topic 99 ... Environmental and Agricultural Bioremediation
  Topic 100 ... In Vivo Directed Evolution
  Topic 101 ... Biosensing and Bioremediation of Toxins
  Topic 102 ... Environmental Bioremediation
  Topic 103 ... Synthetic Biology for Sustainable Paper Manufacturing and Recycling
  Topic 104 ... Global Health Diagnostics
  Topic 105 ... Synthetic Biology for Environmental and Health Solutions
  Topic 106 ... Synthetic Biology for Mercury Bioremediation
  Topic 107 ... Synthetic Biology-Driven Viral Vector Engineering for Therapeutics
  Topic 108 ... Synthetic Biology for Color, Material, and Biofuel Engineering
  Topic 109 ... Synthetic Biology for Disease Detection and Therapeutics
  Topic 110 ... Synthetic Biology for Biological Computing
  Topic 111 ... Synthetic Biology for Environmental Bioremediation
  Topic 112 ... Synthetic Biology for Therapeutic and Material Innovations
  Topic 113 ... Synthetic Biology-Driven Probiotic Therapeutics and Health Solutions
  Topic 114 ... Synthetic Biology for Diagnostic and Forensic Innovation
  Topic 115 ... Synthetic Biology Tools and Community Innovation
  Topic 116 ... Non-Model Bacteria Engineering
  Topic 117 ... Synthetic Biology for Therapeutic and Diagnostic Innovation
  Topic 118 ... Synthetic Genetic Switches and Regulatory Circuits
  Topic 119 ... Microbial Engineering and Biosensing
  Topic 120 ... Synthetic Biology for Resource Optimization and Therapeutic Production
  Topic 121 ... Synthetic Biology for Sustainable Agriculture and Ecosystem Management
  Topic 122 ... Synthetic Biology in Cancer Immunotherapy
  Topic 123 ... Synthetic Biology for Dynamic Control and Optimization
  Topic 124 ... Synthetic Biology for Biosensing and Biological System Engineering
  Topic 125 ... Synthetic Biology Biosensors
  Topic 126 ... Environmental Synthetic Biology
  Topic 127 ... Synthetic Biology for Sustainable Textiles
  Topic 128 ... Synthetic Biology for Fungal and Microbial Disease Detection and Control
  Topic 129 ... Microbial Synthetic Biology for Kidney Disease Treatment
  Topic 130 ... Synthetic Biology-Based Biological Detection Systems
  Topic 131 ... Celiac Disease Synthetic Biology
  Topic 132 ... Protein Engineering and Functional Modulation
  Topic 133 ... Synthetic Biology for Sleep and Mental Health
  Topic 134 ... Sustainable Bioproduction in Synthetic Biology
  Topic 135 ... Synthetic Biology for Targeted Antimicrobial and Microbiome Therapeutics
  Topic 136 ... Synthetic Biology for Metabolic Engineering and Sustainable Chemical Production
  Topic 137 ... DNA Detection and Diagnostics
  Topic 138 ... Synthetic Biology for Environmental Remediation and Biosensing
  Topic 139 ... Environmental Water Biosensing and Remediation
  Topic 140 ... Synthetic Biology for Soil and Land Restoration
  Topic 141 ... Synthetic Biology for Sustainable Food and Packaging Innovations
  Topic 142 ... Synthetic Biology for Environmental and Industrial Innovation
  Topic 143 ... Synthetic Biology for Therapeutic and Ecological Innovation
  Topic 144 ... CRISPR Synthetic Biology
  Topic 145 ... Synthetic Biology for Sustainable Agriculture
  Topic 146 ... Synthetic Biological Computing and Logic Circuits
  Topic 147 ... Synthetic Biology for Biosensing and Health Monitoring
  Topic 148 ... Synthetic Biology for Cancer Diagnosis and Targeted Bacterial Therapy
  Topic 149 ... Synthetic Biology for Water Treatment
  Topic 150 ... Synthetic Biology for Plastic Waste Valorization and Sustainable Energy
  Topic 151 ... Synthetic Biology for Nitrogen Monitoring
  Topic 152 ... Synthetic Biology for Neurodegenerative Diseases
  Topic 153 ... Synthetic Biology Biosensors
  Topic 154 ... Environmental Bioremediation Synthetic Biology
  Topic 155 ... Environmental Biosensing and Safety
  Topic 156 ... Microbial Genetic Parts and Tools
  Topic 157 ... Environmental Biosensing
  Topic 158 ... Synthetic Biology for Eye Disease Prevention and Treatment
  Topic 159 ... CRISPR Diagnostic Technologies
  Topic 160 ... Temperature-Responsive and Signal-Activated Genetic Regulation

,topic,name,description,raw_description
0,0,Synthetic Biology-Enabled Disease Diagnostics ...,This cluster focuses on the advancement of inn...,The common topic of these texts is the develop...
1,1,Light-Inducible Systems,This cluster centers on the development and ap...,The main topic of this cluster is **Light-Indu...
2,2,Synthetic Biology for Microbial Detection and ...,This cluster focuses on harnessing synthetic b...,The main topic of this cluster is the applicat...
3,3,Synthetic Biology for PET Plastic Degradation ...,This cluster focuses on leveraging synthetic b...,The common topic across these texts is the app...
4,4,Synthetic Biology for Cancer and Disease Thera...,This cluster centers on leveraging synthetic b...,The common topic of this cluster is **Syntheti...
...,...,...,...,...
156,156,Microbial Genetic Parts and Tools,This cluster focuses on advancing the toolkit ...,The main topic of this cluster is the developm...
157,157,Environmental Biosensing,This collection of works centers on harnessing...,The common topic across these texts is the app...
158,158,Synthetic Biology for Eye Disease Prevention a...,The collective focus of these works centers on...,The common topic of these texts is the applica...
159,159,CRISPR Diagnostic Technologies,The collective focus of these texts centers on...,The common topic of these texts is the applica...
160,160,Temperature-Responsive and Signal-Activated Ge...,This cluster focuses on the advancement of gen...,The common topic across these texts is the dev...

## 4. Name SynBio Papers topics

In [8]:
print('Naming SynBio Papers topics...')
papers_names = name_topics(papers_df, papers_info)
papers_names

Naming SynBio Papers topics...
  Topic 0 ... Genetic Circuit Engineering
  Topic 1 ... Synthetic Nucleic Acid Engineering
  Topic 2 ... Plant Biosynthetic Pathways
  Topic 3 ... Synthetic CpG ODNs in Immunomodulation
  Topic 4 ... Ethics and Governance of Synthetic Biology
  Topic 5 ... Genetic Circuits and Logic Devices
  Topic 6 ... Oligonucleotide Modification and Immobilization
  Topic 7 ... Synthetic Genome Engineering
  Topic 8 ... Yeast Gene Regulation Cluster
  Topic 9 ... Synthetic Biological Systems and Circuits
  Topic 10 ... Synthetic Biology-Driven Biomaterials
  Topic 11 ... DNA Repair and Epigenetics
  Topic 12 ... Synthetic Biology Design and Modeling
  Topic 13 ... RNA Regulatory Systems
  Topic 14 ... Synthetic Biology in Cancer Immunotherapy
  Topic 15 ... Synthetic Protein Engineering
  Topic 16 ... DNA Nanotechnology
  Topic 17 ... Synthetic Biology in Gene Cloning and Protein Expression
  Topic 18 ... Synthetic Biology in Biomedical Engineering
  Topic 19 ... Plant Gene Regulation
  Topic 20 ... Nanotech Synthetic Biology for Cancer Therapy
  Topic 21 ... DNA Data Storage
  Topic 22 ... Synthetic Biology in Infectious Disease Diagnostics and Vaccine Development
  Topic 23 ... Synthetic Biology-Driven Biocatalytic Innovation
  Topic 24 ... Cell-Free Synthetic Biology
  Topic 25 ... Synthetic Biology for Precise Genetic Control
  Topic 26 ... Bacterial Cancer Therapeutics
  Topic 27 ... Microbial Terpenoid Synthetic Biology
  Topic 28 ... Synthetic Biology Education and Outreach
  Topic 29 ... Natural Product Biosynthesis in Actinomycetes
  Topic 30 ... Gene Discovery and Functional Characterization
  Topic 31 ... Optogenetics and Light-Controlled Synthetic Biology
  Topic 32 ... DNA Assembly and Cloning Technologies
  Topic 33 ... Synthetic Cell-like Compartments
  Topic 34 ... DNA Engineering and Synthetic Nucleotides
  Topic 35 ... Plastic Waste Biodegradation and Upcycling
  Topic 36 ... Synthetic Biology for Microbial Diagnostics and Therapeutics
  Topic 37 ... Synthetic Cell Engineering
  Topic 38 ... Quorum Sensing and Cell Communication in Synthetic Biology
  Topic 39 ... Aptamer and SOMAmer Technologies
  Topic 40 ... Cyanobacterial Synthetic Biology
  Topic 41 ... Biosecurity and Safety in Synthetic Biology
  Topic 42 ... Protein Engineering and Secretion in Bacteria
  Topic 43 ... PCR-Based Genetic Detection of Pathogenic Microorganisms
  Topic 44 ... Genetic System Engineering
  Topic 45 ... Genetic and Protein Engineering
  Topic 46 ... Synthetic Biology and the Engineering of Life Systems
  Topic 47 ... Standardized DNA Assembly
  Topic 48 ... Phage Synthetic Biology
  Topic 49 ... Neurochemical Mapping in Neurosynthetic Biology
  Topic 50 ... Synthetic Biology-Enabled Living and Hybrid Materials
  Topic 51 ... RNA-Nucleic Acid Interactions in Synthetic Biology
  Topic 52 ... Synthetic Biology Innovation and Governance
  Topic 53 ... Synthetic Biology in Immunology and Blood Group Research
  Topic 54 ... Cytoskeletal Engineering in Synthetic Cells
  Topic 55 ... Industrial Synthetic Biology
  Topic 56 ... Microfluidic Platforms for Synthetic Biology
  Topic 57 ... Advances in Synthetic Biology Technologies
  Topic 58 ... Microbial and Yeast Bioproduction
  Topic 59 ... Coronavirus Vaccine Synthetic Biology
  Topic 60 ... Viral Inhibition and Gene Regulation
  Topic 61 ... Synthetic Biology of Viral RNA Systems
  Topic 62 ... Synthetic Biology for Therapeutic Cellular Engineering
  Topic 63 ... Electrochemical DNA Sensors
  Topic 64 ... DNA Nanotechnology for Membrane Engineering
  Topic 65 ... Vascular Gene Regulation and Receptor Engineering
  Topic 66 ... Synthetic Biology for Pathogen Detection
  Topic 67 ... Synthetic Cell and Protocell Engineering
  Topic 68 ... Synthetic Biology for Sustainable Microbial Production and Bioremediation
  Topic 69 ... Biomass Conversion Synthetic Biology
  Topic 70 ... Synthetic Oligonucleotide Diagnostics in Hemoglobinopathies
  Topic 71 ... Synthetic Epigenetics and Genome Stability
  Topic 72 ... Nuclear Receptor Regulation in Synthetic Biology
  Topic 73 ... Synthetic Biology for Environmental Monitoring and Remediation
  Topic 74 ... Fungal Enzyme Regulation
  Topic 75 ... CRISPR Control in Synthetic Biology
  Topic 76 ... Genetic Code Expansion and Translational Engineering
  Topic 77 ... Synthetic Biology and Evolution
  Topic 78 ... Synthetic Biology for Cancer Diagnostics
  Topic 79 ... Bioelectrochemical Synthetic Biology
  Topic 80 ... Synthetic Biology for Sustainable Food and Environmental Systems
  Topic 81 ... Viral Genome Engineering
  Topic 82 ... PKS Engineering
  Topic 83 ... DNA-Modification Enzymes in Synthetic Biology
  Topic 84 ... Mass Spectrometry in Nucleic Acid Analysis
  Topic 85 ... Nucleic Acid Engineering
  Topic 86 ... Synthetic Biology for Plant Virus Detection and Protection
  Topic 87 ... Antimicrobial Resistance and Synthetic Biology
  Topic 88 ... Synthetic Biology for Sustainable Agriculture
  Topic 89 ... Synthetic Biology Tools for Cellular Sensing, Imaging, and Responsive Systems
  Topic 90 ... Synthetic Biology in Lipid and Metabolic Regulation
  Topic 91 ... Synthetic Vesicles and Membrane Engineering
  Topic 92 ... Gene Regulation and Transcription Control
  Topic 93 ... Synthetic Biology for Toxin and Therapeutic Engineering
  Topic 94 ... CRISPR-based Gene Regulation in Bacteria
  Topic 95 ... Synthetic Biology and Artistic Design for Societal Engagement
  Topic 96 ... Synthetic Biology and Expanded Genetic Systems
  Topic 97 ... Synthetic Biosensors and High-Throughput Screening
  Topic 98 ... Yeast Synthetic Biology Engineering
  Topic 99 ... Synthetic Biology-Driven Molecular and Bio-Nano Communication Systems
  Topic 100 ... Synthetic Biology for Sustainable Agriculture
  Topic 101 ... DNA Damage and Repair in Synthetic Biology
  Topic 102 ... Synthetic Biology in Surgical Reconstruction and Regenerative Medicine
  Topic 103 ... Microsatellite and Repetitive DNA Analysis in Synthetic Biology
  Topic 104 ... Interferon Synthetic Biology
  Topic 105 ... Droplet Interface Bilayers Microfluidics
  Topic 106 ... GUV Fabrication and Characterization
  Topic 107 ... Synthetic Biology for Gene Regulation and Cancer Therapy
  Topic 108 ... Genome Engineering Techniques
  Topic 109 ... Genetic Circuit Optimization and Systems Design
  Topic 110 ... Synthetic Vesicle and Membrane Engineering
  Topic 111 ... Synthetic DNA Construction and Assembly Technologies
  Topic 112 ... Synthetic Biological Compartments
  Topic 113 ... AI-Driven Imaging and Data Analysis
  Topic 114 ... Synthetic Oligonucleotide Diagnostics
  Topic 115 ... Synthetic Biology for Ecosystem Restoration
  Topic 116 ... RNA Nanostructures and Devices
  Topic 117 ... Synthetic Nucleic Acids in Immunomodulation
  Topic 118 ... Synthetic Biology for Adaptive and Intelligent Biological Systems
  Topic 119 ... Synthetic Biology for Microencapsulation and Artificial Cells
  Topic 120 ... Spider Silk Engineering
  Topic 121 ... AI-Driven Regulatory Element Design
  Topic 122 ... Synthetic Biology in Viral Vaccine Development and Biosecurity
  Topic 123 ... Peptide Natural Product Engineering
  Topic 124 ... Synthetic Biology for Environmental and Ecological Risk Management
  Topic 125 ... Societal and Ethical Dimensions of Synthetic Biology
  Topic 126 ... Cytokine Engineering in Synthetic Biology
  Topic 127 ... cDNA Cloning and Expression
  Topic 128 ... Synthetic Biology Applications
  Topic 129 ... Standardized Biological Parts
  Topic 130 ... Gene Regulation in Growth Factors and Hormones
  Topic 131 ... Synthetic Biology and Genetic Engineering
  Topic 132 ... Magnetically Controlled Synthetic Biological Systems and Nanomaterials
  Topic 133 ... Microbial Bioengineering
  Topic 134 ... Synthetic Nucleic Acid Design
  Topic 135 ... Gene Regulation in Viral and Mammalian Systems
  Topic 136 ... Synthetic Promoter Engineering in Yeast
  Topic 137 ... Synthetic DNA Design and Engineering Tools
  Topic 138 ... Synthetic Biology for Self-Reproducing and Intelligent Systems
  Topic 139 ... Computational Metabolic Modeling
  Topic 140 ... Synthetic Biology Applications and Regulation
  Topic 141 ... Synthetic Biology Biosensing
  Topic 142 ... SBOL Standardization
  Topic 143 ... Synthetic Biology Approaches to Immune Modulation and Gene Delivery
  Topic 144 ... Microbial Community Engineering
  Topic 145 ... Synthetic Biology-Driven Autonomous Therapeutic Systems
  Topic 146 ... Synthetic Biology for Sustainable Pest Resistance and Crop Enhancement
  Topic 147 ... Synthetic Biology for Sustainable Innovation
  Topic 148 ... Plant Synthetic Biology and Modular Genetic Engineering
  Topic 149 ... Synthetic Biology in Viral Engineering and Gene Therapy
  Topic 150 ... Synthetic Biology-Driven Vaccine Development
  Topic 151 ... Synthetic Biology in Plant Resilience
  Topic 152 ... Bacterial Microcompartments and Surface Layers
  Topic 153 ... Synthetic Biology for Space Exploration
  Topic 154 ... Viral Pathogen Synthetic Biology
  Topic 155 ... Synthetic Nucleic Acid Chemistry
  Topic 156 ... Synthetic Biology Applications and Safety
  Topic 157 ... Synthetic Biology for Sustainable Construction and Environmental Material Production
  Topic 158 ... Membrane and Vesicle Synthetic Biology
  Topic 159 ... Synthetic Biology for Gene Regulation and Therapeutics
  Topic 160 ... Microbial Cell Factory Engineering
  Topic 161 ... Gene and Protein Engineering
  Topic 162 ... Synthetic Biology of Signal Transduction and Gene Regulation Systems
  Topic 163 ... Cytokine Gene Regulation in Synthetic Biology
  Topic 164 ... Ras Oncogene Cluster
  Topic 165 ... Synthetic Yeast Genome Engineering
  Topic 166 ... Metal Regulation and Cofactor Biosynthesis in Synthetic Biology
  Topic 167 ... Ribosomal RNA and Gene Engineering
  Topic 168 ... Synthetic Promoter Engineering in Mammalian Cells
  Topic 169 ... CRISPR Synthetic Biology
  Topic 170 ... Transcription Factor Engineering in Synthetic Biology
  Topic 171 ... Synthetic Nucleic Acid Replication and Self-Assembly
  Topic 172 ... Synthetic Biology in Cancer Therapy
  Topic 173 ... Microbial Bioproduction
  Topic 174 ... Neurodegenerative Synthetic Biology
  Topic 175 ... Synthetic Biology and Systems Biology Policy Cluster
  Topic 176 ... Synthetic TLR Agonists in Cancer Immunotherapy
  Topic 177 ... Synthetic Biology for Cellular Regulation and System Engineering
  Topic 178 ... Synthetic Biology-Enhanced Molecular Diagnostics and Environmental Monitoring
  Topic 179 ... Large DNA Virus Genome Engineering
  Topic 180 ... Metallic Particle Biointeractions and Toxicity
  Topic 181 ... Cell-Free Synthetic Biology
  Topic 182 ... Glycoengineering Cluster
  Topic 183 ... Bacterial Translation and RNA Engineering
  Topic 184 ... Synthetic Gene Regulation and Circuit Engineering
  Topic 185 ... Synthetic Biology for Plant Hormone Signaling
  Topic 186 ... Synthetic Biology for Pattern Formation and Morphogenetic Engineering
  Topic 187 ... Governance and Responsible Innovation in Synthetic Biology
  Topic 188 ... Synthetic Oligodeoxynucleotides in Cancer Immunotherapy
  Topic 189 ... Synthetic Biology for Environmental and Microbial Applications
  Topic 190 ... Synthetic DNA Crown Cells Cluster
  Topic 191 ... Multienzyme Scaffolding and Immobilization
  Topic 192 ... DNA Charge Transfer
  Topic 193 ... High-Throughput Genetic Engineering
  Topic 194 ... Sustainable Biopolymer and Bioremediation Cluster
  Topic 195 ... Synthetic Nucleic Acid Tools
  Topic 196 ... Algal Biorefineries
  Topic 197 ... Synthetic Biology for Carbon Fixation and Bioproduction
  Topic 198 ... Synthetic Biology for Antimicrobial Peptide Development
  Topic 199 ... Synthetic Transcriptional Control and Logic Circuits
  Topic 200 ... Machine Learning in Synthetic Biology
  Topic 201 ... Microalgal Synthetic Biology
  Topic 202 ... Synthetic Oligonucleotide Therapeutics
  Topic 203 ... Fungal Natural Product Synthetic Biology
  Topic 204 ... Synthetic Biology for Enzyme Engineering and Redox System Innovation
  Topic 205 ... Synthetic Biology Biosensing
  Topic 206 ... Yeast Synthetic Biology
  Topic 207 ... Synthetic Protease-Based Signaling and Molecular Switches
  Topic 208 ... Thyroid Hormone Receptor Synthetic Biology
  Topic 209 ... Synthetic DNA Tracers
  Topic 210 ... RAS Mutations in Hematologic Cancers
  Topic 211 ... DNA Structural Dynamics
  Topic 212 ... Microbial Chassis Engineering
  Topic 213 ... Synthetic Vesicle-Based Biological Systems
  Topic 214 ... Synthetic Biology of Transcriptional Regulation in Mammalian Cells
  Topic 215 ... Synthetic Biology and Biological-Cognitive Systems Engineering
  Topic 216 ... RNA Design and Structural Characterization
  Topic 217 ... Biofuel Synthetic Biology
  Topic 218 ... Synthetic Cell Compartments
  Topic 219 ... DNA-Interacting Metal Complexes in Synthetic Biology
  Topic 220 ... Synthetic Biology Automation
  Topic 221 ... RNA-Based Synthetic Gene Regulation
  Topic 222 ... Microfluidic and Cell-Free Platforms
  Topic 223 ... Programmable Biological Systems
  Topic 224 ... DNA Repair in Synthetic Biology
  Topic 225 ... Viral Synthetic Biology
  Topic 226 ... Membrane Engineering
  Topic 227 ... Synthetic Biology of Muscle Gene Regulation
  Topic 228 ... Synthetic Biology of Translation and Resource Allocation
  Topic 229 ... Bacterial Diagnostics and Pathogen Identification
  Topic 230 ... Synthetic Biology in Cancer Vaccines
  Topic 231 ... Synthetic Oligonucleotide Design
  Topic 232 ... Gene Expression Optimization
  Topic 233 ... Synthetic Biology in Cancer Genomics
  Topic 234 ... Synthetic Biology and AI in Contemporary Technoscience
  Topic 235 ... Synthetic RNA Regulatory Circuits
  Topic 236 ... Biological Nanocompartments and Living Materials
  Topic 237 ... Essential Gene Identification
  Topic 238 ... Starch Biosynthesis Regulation
  Topic 239 ... Synthetic Biology for Sustainable Innovation
  Topic 240 ... Synthetic Biology for Tissue Engineering and Regenerative Medicine
  Topic 241 ... Synthetic Biology in Disease Mechanism and Therapeutic Development
  Topic 242 ... Yeast Heat Shock Response Pathways
  Topic 243 ... Synthetic DNA Nanostructures
  Topic 244 ... Dynamic Control Systems
  Topic 245 ... Synthetic Life Boundaries
  Topic 246 ... Synthetic Morphogenesis and Self-Organization
  Topic 247 ... Synthetic Biological Circuits and Devices
  Topic 248 ... AI and Machine Learning in Synthetic Biology
  Topic 249 ... Synthetic Biology-Enabled Advanced Manufacturing and Materials Integration
  Topic 250 ... Cytogenetic and Genomic Tools in Synthetic Biology
  Topic 251 ... Expanded Genetic Alphabet
  Topic 252 ... Nucleic Acid-Nanomaterial Hybrid Systems
  Topic 253 ... DNA Nanotechnology in Cell Engineering
  Topic 254 ... Biofilm Synthetic Biology
  Topic 255 ... Synthetic Biology Data Management and Design Platforms
  Topic 256 ... Vaccine and Immunotherapy Synthetic Biology
  Topic 257 ... Open-Source Measurement Platforms
  Topic 258 ... Chloroplast and Plastid Genome Engineering
  Topic 259 ... CRISPR Yeast Synthetic Biology
  Topic 260 ... Computational Synthetic Biology
  Topic 261 ... DNA Repair Systems in Synthetic Biology
  Topic 262 ... Flavivirus Vaccine and Therapy Development

,topic,name,description,raw_description
0,0,Genetic Circuit Engineering,This cluster centers on the engineering and re...,The common topic of this cluster is the design...
1,1,Synthetic Nucleic Acid Engineering,This cluster centers on the application of syn...,The common topic of these texts is the applica...
2,2,Plant Biosynthetic Pathways,This collection of texts focuses on leveraging...,The common topic of these texts is the applica...
3,3,Synthetic CpG ODNs in Immunomodulation,This cluster centers on the immunostimulatory ...,The common topic of this cluster is the immuno...
4,4,Ethics and Governance of Synthetic Biology,This cluster focuses on the multifaceted ethic...,"The common topic of this cluster is **Ethical,..."
...,...,...,...,...
258,258,Chloroplast and Plastid Genome Engineering,The collective focus of these texts centers on...,The common topic across these texts is **Synth...
259,259,CRISPR Yeast Synthetic Biology,This cluster centers on the utilization and en...,The main topic of this cluster is the applicat...
260,260,Computational Synthetic Biology,This cluster centers on the development and ut...,The common topic across these texts is the dev...
261,261,DNA Repair Systems in Synthetic Biology,The cluster focuses on the integral role of Pr...,The main topic of this cluster is the role of ...
262,262,Flavivirus Vaccine and Therapy Development,This cluster focuses on the application of adv...,The common topic of these texts is the develop...

## 5. Save results

In [9]:
teams_names.to_csv(os.path.join(MODELS_DIR, 'teams_topic_names.txt'), sep='\t', index=False)
papers_names.to_csv(os.path.join(MODELS_DIR, 'papers_topic_names.txt'), sep='\t', index=False)

print(f'Saved to {MODELS_DIR}')
for f in sorted(os.listdir(MODELS_DIR)):
    print(f'  {f}')

Saved to ../assets/topic_models
  papers_doc_topics.txt
  papers_grid_search.txt
  papers_topic_info.txt
  papers_topic_model
  papers_topic_names.txt
  teams_doc_topics.txt
  teams_grid_search.txt
  teams_topic_info.txt
  teams_topic_model
  teams_topic_names.txt